<a href="https://colab.research.google.com/github/knoppin1/DATA-690-WANG/blob/master/Assignment_04/Assignment_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment xx

### Ken Noppinger (knoppin1@umbc.edu)

- Explore College Scorecard website - https://collegescorecard.ed.gov/
- Explore College Scorecard Data web page - https://collegescorecard.ed.gov/data/
- Download and skim the documentation - https://collegescorecard.ed.gov/assets/FullDataDocumentation.pdf
- Download the dataset - https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data.zip (265MB Zip File)
- Unzip the file into a folder (there are many files, one for each school year)
- Import the 2017-2018 school year file "MERGED2017_18_PP.csv" and explore:

    - How many colleges or rows?
    - How many variables or columns?
    - Look at the first 20 rows
    - Look at the last 20 rows
    - Look at a random sample of 20 rows

 There are too many variables to explore, many of which are not interesting. 

 So, modify your import statement to only import the following 9 variables:

    - UNITID
    - INSTNM
    - CITY
    - STABBR
    - ZIP
    - ADM_RATE
    - UGDS
    - TUITIONFEE_IN
    - MN_EARN_WNE_P10

- Download and read the data dictionary file - https://collegescorecard.ed.gov/assets/CollegeScorecardDataDictionary.xlsx

 Find out the definition of the above 9 variables and document the definitions in the Jupyter Notebook so that the readers will not need to repeat the research to know the meaning of these variables.

---

In [1]:
# Import libraries
import pandas as pd

In [2]:
# load the 2017-2018 school year file "MERGED2017_18_PP.csv" 
df = pd.read_csv('MERGED2017_18_PP.csv')  
df

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (1729) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

        UNITID    OPEID  ...  FTFTPCTFLOAN_POOLED_SUPP SCUGFFN_POOLED
0       100654   100200  ...                       NaN            NaN
1       100663   105200  ...                       NaN            NaN
2       100690  2503400  ...                       NaN            NaN
3       100706   105500  ...                       NaN            NaN
4       100724   100500  ...                       NaN            NaN
...        ...      ...  ...                       ...            ...
7107  48312404   108163  ...                       NaN            NaN
7108  48387801  4223701  ...                       NaN            NaN
7109  48400201  4228101  ...                       NaN            NaN
7110  48778201  4221501  ...                       NaN            NaN
7111  49005401  4182601  ...                       NaN            NaN

[7112 rows x 1986 columns]

In [3]:
# Find out how many colleges or rows?   
# Find out how many variables or columns? 
df.shape

(7112, 1986)

In [4]:
# Number of colleges
len(df.index)

7112

In [5]:
# Number of attributes (columns)
len(df.columns)

1986

In [6]:
# Look at the first 20 rows 
df.head(20)

    UNITID    OPEID  ...  FTFTPCTFLOAN_POOLED_SUPP SCUGFFN_POOLED
0   100654   100200  ...                       NaN            NaN
1   100663   105200  ...                       NaN            NaN
2   100690  2503400  ...                       NaN            NaN
3   100706   105500  ...                       NaN            NaN
4   100724   100500  ...                       NaN            NaN
5   100751   105100  ...                       NaN            NaN
6   100760   100700  ...                       NaN            NaN
7   100812   100800  ...                       NaN            NaN
8   100830   831000  ...                       NaN            NaN
9   100858   100900  ...                       NaN            NaN
10  100937   101200  ...                       NaN            NaN
11  101028  1218200  ...                       NaN            NaN
12  101073  1055400  ...                       NaN            NaN
13  101116  1303906  ...                       NaN            NaN
14  101143   101500  ...                       NaN            NaN
15  101161   106000  ...                       NaN            NaN
16  101189   100300  ...                       NaN            NaN
17  101240   101700  ...                       NaN            NaN
18  101277  4187200  ...                       NaN            NaN
19  101286   101800  ...                       NaN            NaN

[20 rows x 1986 columns]

In [7]:
# Look at the last 20 rows 
df.tail(20)

        UNITID    OPEID  ...  FTFTPCTFLOAN_POOLED_SUPP SCUGFFN_POOLED
7092  47503311  4208611  ...                       NaN            NaN
7093  47503312  4208612  ...                       NaN            NaN
7094  47503313  4208613  ...                       NaN            NaN
7095  47647001  4088301  ...                       NaN            NaN
7096  47662901  4189101  ...                       NaN            NaN
7097  47691101  4205801  ...                       NaN            NaN
7098  48065701   869423  ...                       NaN            NaN
7099  48079001  4218901  ...                       NaN            NaN
7100  48092101  4220001  ...                       NaN            NaN
7101  48133101  4213501  ...                       NaN            NaN
7102  48154401  4220901  ...                       NaN            NaN
7103  48305401  4224601  ...                       NaN            NaN
7104  48312401   108131  ...                       NaN            NaN
7105  48312402   108161  ...                       NaN            NaN
7106  48312403   108162  ...                       NaN            NaN
7107  48312404   108163  ...                       NaN            NaN
7108  48387801  4223701  ...                       NaN            NaN
7109  48400201  4228101  ...                       NaN            NaN
7110  48778201  4221501  ...                       NaN            NaN
7111  49005401  4182601  ...                       NaN            NaN

[20 rows x 1986 columns]

In [8]:
# Look at a random sample of 20 rows 
df.sample(n=20, random_state=1)

        UNITID    OPEID  ...  FTFTPCTFLOAN_POOLED_SUPP SCUGFFN_POOLED
3205    217624   341700  ...                       NaN            NaN
4775    436030  3327300  ...                       NaN            NaN
4109    364548  1071700  ...                       NaN            NaN
4482    413626  3096400  ...                       NaN            NaN
3506    227429   360200  ...                       NaN            NaN
6726  13090702  1172703  ...                       NaN            NaN
5642    457952  4158000  ...                       NaN            NaN
5523    455840  4147700  ...                       NaN            NaN
3099    214829   332918  ...                       NaN            NaN
420     120953   125900  ...                       NaN            NaN
4177    368452  2578200  ...                       NaN            NaN
1750    173258   234000  ...                       NaN            NaN
6582    489858  3698307  ...                       NaN            NaN
5784    460701  3816301  ...                       NaN            NaN
4845    439482  3294306  ...                       NaN            NaN
1822    175342   239600  ...                       NaN            NaN
4053    250601  2100614  ...                       NaN            NaN
1028    147776   169300  ...                       NaN            NaN
3201    217572   659100  ...                       NaN            NaN
1892    177579  1027900  ...                       NaN            NaN

[20 rows x 1986 columns]

---
Read (with naked eyes, not computer) the dictionary and find out the definitions of the following 12 columns and copy the text next to the column name.
*   ***UNITID***:  Unique identification number assigned to postsecondary institutions
*   ***INSTNM***:  Name of institution
*   ***CITY***: City of institution's location
*   ***ZIP***: Zip code of institution's location
*   ***STABBR***: State abreviation of institution's location
*   ***ADM_RATE***: Fall Admission rate for institution. Number of admitted undergraduates divided by number of applicants
*   ***UGDS***: Number of degree/certificate-seeking undergraduates enrolled in the fall
*   ***TUITIONFEE_IN***: In-state tuition fees
*   ***MN_EARN_WNE_P10***: Mean earnings for institutional aggregate of all federally aided students who enroll in an institution each year and who are
employed but not enrolled.  This mean reflects 10 years after enrollment.

In [9]:
# Re-import the data with above 9 columns (ignore all other variables)
columns_of_interest = ['UNITID', 'INSTNM', 'CITY', 'ZIP', 'STABBR', 'ADM_RATE', 'UGDS', 'TUITIONFEE_IN', 'MN_EARN_WNE_P10']
colleges_df = pd.read_csv('MERGED2017_18_PP.csv', header = 0, usecols = columns_of_interest)  
colleges_df.shape

(7112, 9)

In [10]:
colleges_df.head(4).T

                                        0  ...                                    3
UNITID                             100654  ...                               100706
INSTNM           Alabama A & M University  ...  University of Alabama in Huntsville
CITY                               Normal  ...                           Huntsville
STABBR                                 AL  ...                                   AL
ZIP                                 35762  ...                                35899
ADM_RATE                           0.9027  ...                               0.8123
UGDS                                 4824  ...                                 6917
TUITIONFEE_IN                        9857  ...                                10280
MN_EARN_WNE_P10                       NaN  ...                                  NaN

[9 rows x 4 columns]

In [11]:
# Find out the 10 colleges that are hardest to get in (top 10)
colleges_df.sort_values(by=['ADM_RATE','UGDS'], ascending=True).head(10)

      UNITID  ... MN_EARN_WNE_P10
6112  480912  ...             NaN
5226  448309  ...             NaN
2974  211635  ...             NaN
6664  491288  ...             NaN
2978  211893  ...             NaN
3979  243744  ...             NaN
1557  166027  ...             NaN
2302  192110  ...             NaN
2233  190150  ...             NaN
2123  186131  ...             NaN

[10 rows x 9 columns]

In [12]:
# Find out the average in-state tuition of top 10
top10_expensive_df = colleges_df.sort_values(by=['TUITIONFEE_IN'], ascending=False).head(10)
top10_expensive_df["TUITIONFEE_IN"].mean()

57050.4

In [13]:
# Find out the average earnings of graduates from the top 10
top10_earnings_df = colleges_df.sort_values(by=['MN_EARN_WNE_P10'], ascending=False).head(10)
top10_earnings_df["MN_EARN_WNE_P10"].mean()

nan

In [14]:
# Find out the 10 colleges that are easiest to get in (bottom 10)
colleges_df.sort_values(by=['ADM_RATE','UGDS'], ascending=False).head(10)

      UNITID  ... MN_EARN_WNE_P10
3549  228796  ...             NaN
3364  221485  ...             NaN
1105  151166  ...             NaN
1335  157535  ...             NaN
1982  180522  ...             NaN
1691  170967  ...             NaN
3335  220604  ...             NaN
3072  214290  ...             NaN
1865  176770  ...             NaN
6351  485272  ...             NaN

[10 rows x 9 columns]

In [15]:
# Find out the average in-state tuition of the bottom 10
bot10_expensive_df = colleges_df.sort_values(by=['TUITIONFEE_IN'], ascending=True).head(10)
bot10_expensive_df["TUITIONFEE_IN"].mean()

994.5

In [16]:
# Find out the average earnings of graduates from the bottom 10
bot10_earnings_df = colleges_df.sort_values(by=['MN_EARN_WNE_P10'], ascending=True).head(10)
bot10_earnings_df["MN_EARN_WNE_P10"].mean()

nan